package:
  name: ncl

source:
  svn_url: https://subversion.ucar.edu/ncldev/ncarg/trunk

build:
  detect_binary_files_with_prefix: true
  number: 0
  string: ncdf441_0

requirements:
  build:
    - libpng 1.6.*
    - jasper
    - jpeg
    - zlib
    - hdf4
    - hdf5
    - gcc
    - libnetcdf 4.4.1
    - proj4
    - hdfeos2
    - g2clib
    - libgdal >=2.1.0
    - libiconv
    - hdfeos5 
    - curl
    - cairo [linux]
    - udunits2
    - bzip2
    - szip

  run:
    - libgcc
    - libpng 1.6.*
    - jasper
    - jpeg
    - zlib
    - libnetcdf 4.4.1
    - hdf5
    - hdf4
    - proj4
    - hdfeos2
    - g2clib
    - libgdal >=2.1.0
    - libiconv
    - hdfeos5
    - curl
    - cairo [linux]
    - gcc
    - udunits2
    - bzip2
    - krb5
    - szip

test:
  commands:
    - ncl -V && NCARG_ROOT=${PREFIX} ${SRC_DIR}/install/make-tarfile/check_files | grep '^<' | grep -v '^< bin/ESMF_RegridWeightGen' && exit 1 || exit 0
