package:
  name: ncl

source:
  svn_url: https://subversion.ucar.edu/ncldev/ncarg/trunk

build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libpng 
    - jasper
    - jpeg
    - zlib
    - hdf4
    - hdf5
    - gcc
    - libnetcdf
    - proj4
    - hdfeos2
    - g2clib
    - libgdal >=2.0.0
    - libiconv
    - hdfeos5 
    - curl
    - cairo [linux]
    - udunits2
    - bzip2
    - szip

  run:
    - libgcc
    - libpng
    - jasper
    - jpeg
    - zlib
    - libnetcdf
    - hdf5
    - hdf4
    - proj4
    - hdfeos2
    - g2clib
    - libgdal >=2.0.0
    - libiconv
    - hdfeos5
    - curl
    - cairo [linux]
    - gcc
    - udunits2
    - bzip2
    - krb5
    - szip

test:
  commands:
    - ncl -V && NCARG_ROOT=${PREFIX} ${SRC_DIR}/install/make-tarfile/check_files | grep '^<' | grep -v '^< bin/ESMF_RegridWeightGen' && exit 1 || exit 0
