package:
  name: ncl
  version: "6.4.0"

source:
  svn_url: https://subversion.ucar.edu/ncldev/ncarg/trunk
  svn_rev: 16407

build:
  number: 1
  string: nogdal_1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libpng 
    - jasper
    - jpeg
    - zlib
    - hdf4
    - hdf5
    - gcc
    - libnetcdf
    - proj4
    - hdfeos2
    - g2clib
    - libgdal
    - libiconv
    - hdfeos5 
    - curl
    - cairo [linux]
    - udunits2
    - bzip2

  run:
    - libgcc
    - libpng
    - jasper
    - jpeg
    - zlib
    - libnetcdf
    - hdf5
    - hdf4
    - proj4
    - hdfeos2
    - g2clib
    - libgdal
    - libiconv
    - hdfeos5
    - curl
    - cairo [linux]
    - gcc
    - udunits2
    - bzip2
    - krb5

test:
  commands:
    - ncl -V
